# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "99 Upsell"
client_id = "54f1ab979a3e2891d2c634f59c1f3296"
application_url = "https://chemistry-perform-sponsorship-officers.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_product_listings,read_themes,write_files,write_orders,write_products"

[auth]
redirect_urls = [
  "https://chemistry-perform-sponsorship-officers.trycloudflare.com/auth/callback",
  "https://chemistry-perform-sponsorship-officers.trycloudflare.com/auth/shopify/callback",
  "https://chemistry-perform-sponsorship-officers.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
