# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "scratch-card-dev"
client_id = "923f2480b5099ee12b4c1c84af304fbf"
application_url = "https://stone-phase-attractions-speeds.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://stone-phase-attractions-speeds.trycloudflare.com/auth/callback",
  "https://stone-phase-attractions-speeds.trycloudflare.com/auth/shopify/callback",
  "https://stone-phase-attractions-speeds.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "gearsforcoders.myshopify.com"
